### ISSUE TITLE
Dew Point and Apparent Temperature incorrectly reported as C, but shows as F.

### ISSUE THREAD

**Issue by nocturne1** [naofireblade/homebridge-weather-plus#129]
I have values set to Imperial, and current temp reports correctly as F. However, when looking at dew point or apparent temperature, while it shows the unit as F, the number is clearly C.
Tried with both dark sky as well as openweathermap. Tried the same openweathermap source in the -ws plugin, and F showed up properly, so it's not the data sources themselves.

Screenshots below:
![IMG_0905](https://user-images.githubusercontent.com/3673461/82571032-3a30ba80-9b37-11ea-982a-6653c5275949.jpeg)
![IMG_0904](https://user-images.githubusercontent.com/3673461/82571040-3d2bab00-9b37-11ea-8ae8-6f6b26cb194b.jpeg)

**Comment by nocturne1** [comment]
Interestingly enough, dew point and apparent temperature give proper F data when in Apple mode - but not when reporting in Eve mode.

**Comment by mbierman** [comment]
Yeah, “Temperature Apparent” is definitely not in F.

**Comment by johnschult** [comment]
Min Temperature in Eve is also C.

**Comment by naofireblade** [comment]
Should be fixed in v2.3.4. Can anybody confirm this?

**Comment by johnschult** [comment]
It’s not fixed. The values now read ~50° higher then they should.

**Comment by nicoryan** [comment]
> Should be fixed in v2.3.4. Can anybody confirm this?

This issue still has not yet been fixed. Displays incorrectly.
