### ISSUE TITLE
Apparent Temperature and Dew Point not responding on Apple Home App

### ISSUE THREAD

**Issue by themoddedcube** [naofireblade/homebridge-weather-plus#166]
Hi guys, this plugin is great, installed it yesterday, except the only problem I am having is that the Apparent Temperature and Dew Point are not responding, and I have no idea how to fix it, and help would be appreciated. Thank you and have a great day, and stay safe as well.

**Comment by themoddedcube** [comment]
Now it is responding, but the Dew Point and Apparent Temperature, are the exact same, is this normal?

**Comment by themoddedcube** [comment]
I am so sorry, but now its not working agian lol, it says not responding pls help

**Comment by kylerove** [comment]
I created a pull request to merge fix suggested by @franz2526. https://github.com/naofireblade/homebridge-weather-plus/pull/167

**Comment by naofireblade** [comment]
Do you use the temperature unit C or F?

**Comment by themoddedcube** [comment]
F

**Comment by kylerove** [comment]
Same here. I use F and whenever temp value < 32 was returned one of the temperature based accessories would be unresponsive.

**Comment by naofireblade** [comment]
Fixed in v3.2.3

**Comment by mrMiimo** [comment]
I just updated to the latest version (3.2.3) but temperature sensor still doesn't work ...
